# Generated by Django 3.1.7 on 2021-06-04 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
