# Generated by Django 2.2 on 2021-06-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userfeedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='name',
            field=models.CharField(default='unknown', max_length=70),
        ),
    ]
